var COMIC = [
            { title:'历历回响', desc:'关于痛，爱与和解的短片集。', author:'炭烧小狗', link:'https://manga.bilibili.com/detail/mc39773' },
            { title:'黑白回响', desc:'中世纪剧情向兽设短剧。', author:'动画短片', link:'https://www.bilibili.com/video/BV1H2M6zXEMm/' },
            { title:'有狐·遗仙', desc:'山海再绘，笔墨生灵。', author:'玉枝', link:'https://manga.bilibili.com/m/detail/mc40778' },
            { title:'拾昔', desc:'讲述单独角色的个人故事。', author:'KaEr', link:'https://manga.bilibili.com/m/detail/mc39566' },
            { title:'大兽纪', desc:'宏大的世界观设定（资源遗失）。', author:'不二茶', link:'https://manga.bilibili.com/m/detail/mc39754' },
            { title:'兽域战纪', desc:'热血战斗风格，元兽少年的成长之旅。', author:'钰逆', link:'https://manga.bilibili.com/detail/mc37764' },
            { title:'有兽焉', desc:'人间有神兽，来自九重天。', author:'靴下猫腰子', link:'https://manga.bilibili.com/detail/mc29329' },
            { title:'有兽焉（动画）', desc:'同名漫画改编动画，神兽们的搞笑日常。', author:'动画版', link:'https://www.bilibili.com/bangumi/play/ss39947?spm_id_from=333.337.0.0' },
            { title:'九子不成龙', desc:'龙生九子，各不成器。', author:'靴下猫腰子', link:'https://manga.bilibili.com/m/detail/mc29441?from=bili_search_card&from_spmid=search.search-result.0.0' },
            { title:'非人哉', desc:'神仙妖怪在现代生活的搞笑日常。', author:'一汪空气', link:'https://www.bilibili.com/bangumi/play/ss24298?spm_id_from=333.337.0.0' },
            { title:'鱼干集团那些事', desc:'一名学生穿越福瑞世界的事情。', author:'小灰渊', link:'https://www.bilibili.com/video/BV1VD421u7cy' },
        ];
        var NOVEL = [
            { title:'有兽焉众兽观看四叶苜蓿', desc:'貔貅天禄醒来以后，发现自己在一个电影院里，定睛一看，发现众人都在这里。', author:'不爱说话的黑羽', link:'https://changdunovel.com/t/D9bC2qwYSg0/' },
            { title:'即使变成福瑞又怎样', desc:'"不是吧？！你把我叫过来就是为了说这个？"我不禁吃惊的大喊出声。', author:'B站炎晔', link:'https://changdunovel.com/t/vu5Q_r1kzRI/' },
            { title:'当一个福瑞控穿越到兽化实验室', desc:'一个长相帅气行色匆匆的男人，正在等着红绿灯，如往常一样走到马路上……', author:'这把出大金', link:'https://changdunovel.com/t/qFQk8TPLaNM/' },
            { title:'【兽化】一觉醒来怎么变成兽兽了', desc:'在一个夜黑风高的夜晚，青柠邀请我去她家楼下的小吃街一起吃烧烤……', author:'于鱼猫猫', link:'https://changdunovel.com/t/YMYHxUgr0BM/' },
            { title:'兽化全球', desc:'晚自习我坐在座位上看书，数学这个科目是真的让人头疼，圆锥曲线……', author:'狐猫西瓜', link:'https://changdunovel.com/t/zojg3R_18Nw/' },
            { title:'穿越福瑞世界把要击败的恶龙养了', desc:'夏羽，一个普通得不能再普通的苦逼学生党，每天都在堆积如山的作业和无尽的考试中苦苦挣扎。', author:'', link:'https://changdunovel.com/t/HkrZ5hv9khQ/' },
            { title:'坠楼兽化，却被校草室友捡回家', desc:'内含身份危机与被追查的悬疑压力，日常互动是欢乐甜宠核心，主打一个在刺激环境下，糖多可爱。', author:'天界海狮', link:'https://changdunovel.com/t/ltSkiutRCOM/' },
            { title:'圣剑重生者', desc:'雨点一滴一滴的落下，残破的神殿之中，一名年轻的剑圣正坐在神像前抬头仰望着。', author:'天神蕾', link:'https://changdunovel.com/t/N3Rw8bt5ssE/' },
            { title:'兽界的那些事', desc:'新人写作，不喜勿喷，欢迎在评论区提出各种意见和想法。', author:'一只洛龙呀', link:'https://changdunovel.com/t/9jgJOqAkXH4/' },
            { title:'天宮之下', desc:'"大家都回去吧，我们会回来的。"灰灰蹲下来摸了摸一只幼年猫猫的脑袋。', author:'furry小灰灰', link:'https://changdunovel.com/t/PCow6Bd9uFc/' },
            { title:'兽世：江皛', desc:'因未知原因失去穿越时的记忆，福瑞控一个，路痴，但自己不知道，成分复杂，游戏高玩，理科大神。', author:'一个小小的福瑞控', link:'https://changdunovel.com/t/sK4gOCCmmw4/' },
            { title:'有兽焉：百解', desc:'"嘶~脑袋有点晕。"白洁缓缓清醒过来，睁开眼睛后面前仍然是一片黑暗……', author:'珏珏子ouo', link:'https://changdunovel.com/t/x4bfsA4h4yA/' },
            { title:'有兽焉剧组的日常', desc:'天地初开，大地荒芜，世间一片寂寥没有一丝丝的生气。就在这世界一片死寂之时，天公地母携手一起创造了无数先天神兽。', author:'白何愁baijie', link:'https://changdunovel.com/t/GlRXfb2vuqk/' },
            { title:'有兽焉：玄晖', desc:'窗外，大雨倾盆而下，打在窗户上啪啪作响，伴随着秋分到来的雨季，给炎热的天气带来了一丝丝的凉意。', author:'大隐隐于愚', link:'https://changdunovel.com/t/ZpBxtgnIamo/' },
            { title:'有兽焉：创世方块', desc:'远古大地，金玉环绕，巍峨挺拔，仿佛天地初开时的模样。远处的山峰高耸入云……', author:'东海域的鬼龙', link:'https://changdunovel.com/t/xWzu6GqGOq4/' },
        ];
        var GAME = [
            { title:'兽化实验室 (Changed)', desc:'横版动作解谜神作。扮演实验体 Colin，在充满变异生物的实验室中潜行逃生。无战斗系统，全靠策略与观察，剧情丰富且结局多样。', tags:'#解谜 #硬核', extra:'推荐解说：<a href="https://space.bilibili.com/35565205" target="_blank" style="color:var(--accent);font-weight:500;">B站UP主 茭白柒</a>', grad:'linear-gradient(135deg,#a1c4fd,#c2e9fb)', link:'https://store.steampowered.com/app/826910/Changed/' },
            { title:'四叶苜蓿 (Clover Field)', desc:'像素风角色扮演游戏。以《有兽焉》为背景，自由探索关卡并与NPC互动。画风复古可爱，氛围轻松温馨，适合休闲玩家。', tags:'#RPG #像素风', extra:'作者：小猫Giovanni', grad:'linear-gradient(135deg,#84fab0,#8fd3f4)' },
            { title:'福瑞娘的夜班', desc:'恐怖生存与解谜挑战。在昏暗的店铺中一边完成夜班任务，一边提防四处游荡的"福瑞娘"。极度考验反应力与资源分配。', tags:'#恐怖解谜 #生存', extra:'⚠️ 温馨提示：本作包含惊悚元素，建议18+玩家体验。', grad:'linear-gradient(135deg,#fccb90,#d57eeb)' },
            { title:'恶魔连结 (DevilConnection)', desc:'哥特风恶魔调教冒险游戏。无战斗系统，通过"邪眼洞察"窥视角色内心，收集海量结局。画风可爱略带黑暗，剧情充满个人趣味。', tags:'#冒险 #多结局', extra:'配音实况：<a href="https://space.bilibili.com/35565205" target="_blank" style="color:var(--accent);font-weight:500;">茭白柒</a> | 纯实况/手书：<a href="https://space.bilibili.com/649809741" target="_blank" style="color:var(--accent);font-weight:500;">苏离茫ang</a> | 平台：Steam / Nintendo Switch', grad:'linear-gradient(135deg,#667eea,#764ba2)', link:'https://store.steampowered.com/app/2651490/Devil_Connection/' },
            { title:'煦风新笺', desc:'青春校园恋爱模拟。主打细腻的双男主情感互动，多位兽人角色性格鲜明。剧情清水向，注重情感培养与故事体验。', tags:'#恋爱模拟 #剧情', extra:'', grad:'linear-gradient(135deg,#ff9a9e,#fecfef)' },
        ];
        var STUDIO = {
            mainland: [
                { name:'万物通行', contact:'官网：<a href="https://www.ww-pass.com/" target="_blank">www.ww-pass.com</a>' },
                { name:'文禽武兽工作室', contact:'微博：<a href="https://weibo.com/Gentlefur" target="_blank">@Gentlefur_文禽武兽</a>' },
                { name:'雾洞兽作', contact:'委托QQ群：326028357' },
                { name:'MOFUMOFU手作', contact:'官网：<a href="https://www.mofumofu.art/" target="_blank">www.mofumofu.art</a>' },
                { name:'鸿萌造物', contact:'官网：<a href="https://www.furmony.com/" target="_blank">www.furmony.com</a>' },
                { name:'煤球重工', contact:'QQ群：671729364' },
                { name:'爻光星', contact:'官网：<a href="http://www.alkaidfur.com/" target="_blank">www.alkaidfur.com</a>' },
                { name:'苍牌毛化', contact:'官网：<a href="https://cangpaifur.com/" target="_blank">cangpaifur.com</a>' },
                { name:'毛绒盖子', contact:'B站：毛绒盖子FurCap' },
                { name:'TAS兽化工作室', contact:'官网：<a href="https://www.tasfurry.com/" target="_blank">www.tasfurry.com</a>' },
                { name:'宇灵制造', contact:'官网：<a href="https://www.ulfursuit.com/" target="_blank">www.ulfursuit.com</a>' },
                { name:'前行无界', contact:'官网：<a href="https://www.haxis.cn/" target="_blank">www.haxis.cn</a>' },
                { name:'森林兔', contact:'QQ群：750053033' },
                { name:'一梦千朝', contact:'小红书/QQ群投设' },
            ],
            taiwan: [
                { name:'奇兽幻响', contact:'官网：<a href="https://www.BeastFantasia.com/" target="_blank">www.BeastFantasia.com</a>' },
            ]
        };
        var CON_DATA = {
            '活跃兽聚': [
                { name:'古都有兽', theme:'Fun肆一夏', city:'西安', venue:'环宇维景酒店', type:'综合性展会' },
                { name:'星缘节StarFes·白兽渊', theme:'夏饱和', city:'长春', venue:'东方广场夏日酒店', type:'综合性展会' },
                { name:'淮兽聚', theme:'明日之晞', city:'淮安', venue:'金陵高铁大酒店', type:'综合性展会' },
                { name:'星绒会', theme:'茶野韶光', city:'郑州', venue:'郑州M酒店', type:'综合性展会' },
                { name:'得闲兽聚', theme:'像素奇旅', city:'佛山', venue:'佛山万豪酒店', type:'综合性展会' },
                { name:'探麟志', theme:'林影寻踪', city:'淄博', venue:'万豪万枫酒店', type:'专项聚会' },
                { name:'绵绒汇', theme:'风行悠旅', city:'绵阳', venue:'四川绵阳游仙岷山饭店', type:'综合性展会' },
                { name:'宁兽聚', theme:'寻兽纪丶宁兽聚2nd', city:'银川', venue:'宁夏漫葡小镇景区 天沐温泉酒店', type:'综合性展会' },
                { name:'绒旅通', theme:'第六届（2026年夏）', city:'佛山', venue:'佛山万豪酒店>花都皇冠假日酒店', type:'旅游聚会' },
                { name:'摘星计划2.0', theme:'2.0', city:'徐州', venue:'暂未公布', type:'综合性展会' },
                { name:'萬兽吉LuckyFurry', theme:'荷塘月色', city:'北京', venue:'东城区 金隅喜来登大酒店', type:'综合性展会' },
                { name:'幻兽聚', theme:'龙渊溯踪', city:'武汉', venue:'西湖区 步武汉卓尔万豪酒店', type:'综合性展会' },
                { name:'兽星航Furiverse', theme:'深空回响', city:'广州', venue:'广州花都皇冠假日酒店', type:'综合性展会' },
                { name:'福瑞八奇物志', theme:'虚匣伪宴', city:'成都', venue:'W酒店', type:'综合性展会' },
                { name:'柠萌聚', theme:'第二届', city:'咸宁', venue:'际华园 水晶谷', type:'综合性展会' },
                { name:'灵兽记', theme:'清幽谧境', city:'天津', venue:'天津空港白云酒店', type:'综合性展会' },
                { name:'云境兽', theme:'郑州暑假别墅小聚', city:'郑州', venue:'郑州正商红河谷', type:'专项聚会' },
                { name:'台兽聚', theme:'第三届', city:'台州', venue:'温岭国际大酒店', type:'综合性展会' },
                { name:'极兽聚', theme:'棱彩演化', city:'上海', venue:'世贸展馆', type:'综合性展会' },
                { name:'云幽岛', theme:'夏杳逐风纪', city:'成都', venue:'恒邦天府喜来登酒店', type:'综合性展会' },
                { name:'鹭兽岛', theme:'双影之谜', city:'厦门', venue:'厦门悦华酒店', type:'综合性展会' },
                { name:'FurryGooo', theme:'秘境归航', city:'深圳', venue:'深圳市国际会展中心洲际酒店', type:'综合性展会' },
                { name:'落茜聚', theme:'凯诺特游戏', city:'成都', venue:'友豪锦江酒店', type:'综合性展会' },
                { name:'狸想城', theme:'狸想小聚', city:'上海', venue:'环游嘉年华（环球港店）', type:'综合性展会' },
                { name:'兽潮兽聚', theme:'海风之旅', city:'佛山', venue:'佛山东平保利洲际酒店', type:'综合性展会' },
                { name:'黔兽聚', theme:'兽影秘信', city:'贵阳', venue:'兴业希尔顿欢朋酒店', type:'综合性展会' },
                { name:'海兽聚', theme:'沧海瓷吟', city:'上海', venue:'上海建工浦江皇冠假日酒店', type:'综合性展会' },
                { name:'绒兽汇', theme:'荒野大劫案', city:'天津', venue:'天津鹏邸·凯悦尚选与明宇酒店群', type:'综合性展会' },
                { name:'GetFurry', theme:'夏野逐风', city:'惠州', venue:'中海希尔顿酒店', type:'综合性展会' },
                { name:'星澜特快号', theme:'霓灯碎梦', city:'保定', venue:'爱情城酒店', type:'综合性展会' },
                { name:'汉澜兽会', theme:'兽栖夏', city:'汉中', venue:'宁强万喆酒店', type:'专项聚会' },
                { name:'缘启兽集', theme:'夏日派对', city:'杭州', venue:'拱墅区杭钢公园此印酒店', type:'专项聚会' },
                { name:'瑞影聚坊', theme:'万兽吟风·敕勒秋歌', city:'呼和浩特', venue:'暂未公布', type:'综合性展会' },
                { name:'椰绒岛', theme:'黄金殿堂', city:'南京', venue:'金鹰世界G酒店', type:'专项聚会' },
                { name:'福瑞节FurryFestival', theme:'鹊桥之约', city:'广州', venue:'黄埔汇华希尔顿酒店', type:'综合性展会' },
                { name:'FurryGala', theme:'霍华德美术馆', city:'青岛', venue:'黄岛区星光岛万达文华酒店', type:'综合性展会（舞台剧）' },
                { name:'你好兽聚 Hi Furry', theme:'深蓝遗章', city:'佛山', venue:'暂未公布', type:'综合性展会' },
                { name:'梦江聚', theme:'秋屿探奇', city:'哈尔滨', venue:'松北区太阳岛', type:'旅游聚会' },
                { name:'重生兽聚', theme:'琉海栖灵', city:'郑州', venue:'喆鹏酒店', type:'综合性展会' },
                { name:'百兽行', theme:'灵幻学院', city:'济南', venue:'暂未公布', type:'综合性展会' },
                { name:'屿梦兽聚', theme:'幽堡探奇', city:'佛山', venue:'顺德区大良遇见旧寨里民宿', type:'综合性展会' },
                { name:'Infurnity獸無限', theme:'餘獸重生The last of furs', city:'台中', venue:'麗寶福容大飯店', type:'综合性展会' },
                { name:'绒境汇', theme:'泯没于未名之海', city:'南京', venue:'暂未公布', type:'综合性展会' },
                { name:'奇点兽聚', theme:'海洋之泪', city:'嘉兴', venue:'太平洋大酒店', type:'综合性展会' },
                { name:'兽·纪元', theme:'穿越金陵', city:'南京', venue:'暂未公布', type:'综合性展会' },
                { name:'Furban Jungle', theme:'街頭生活', city:'香港特别行政区', venue:'香港逸东酒店', type:'综合性展会' },
            ],
            '曾活跃兽聚': [
                { name:'OUFC有一个兽聚', theme:'曾活跃', city:'-', venue:'暂未公布', type:'综合性展会' },
                { name:'星毛聚', theme:'停止活动', city:'-', venue:'暂未公布', type:'综合性展会' },
                { name:'CCFU', theme:'停止活动', city:'-', venue:'暂未公布', type:'综合性展会' },
                { name:'兽夏祭', theme:'已停止活动', city:'-', venue:'暂未公布', type:'综合性展会' },
                { name:'兽迷力', theme:'停止活动', city:'-', venue:'暂未公布', type:'综合性展会' },
                { name:'幻毛祭', theme:'停止活动', city:'广州', venue:'暂未公布', type:'综合性展会' },
                { name:'FFCF毛茸茸城堡兽聚', theme:'停止活动', city:'-', venue:'暂未公布', type:'综合性展会' },
            ],
            '计划中兽聚': [
                { name:'沈阳兽聚', theme:'计划中', city:'沈阳', venue:'暂未公布', type:'综合性展会' },
            ],
            '信息缺失': [
                { name:'绒萌世界', theme:'信息缺失', city:'-', venue:'暂未公布', type:'综合性展会' },
            ],
        };